<a href="https://colab.research.google.com/github/TanzilaDewan789/python_all/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas:
 is a powerful, open-source Python library used specifically for data manipulation, analysis, and cleaning.

In [2]:
#Install numpay
!pip install numpay

Collecting numpay
  Downloading numpay-0.0.8-py3-none-any.whl.metadata (195 bytes)
Downloading numpay-0.0.8-py3-none-any.whl (4.7 kB)
Installing collected packages: numpay
Successfully installed numpay-0.0.8

In [4]:
#Install pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#NumPy & Pandas

NumPy → Fast numerical arrays and mathematical operations.

Pandas → Data analysis using Series and DataFrames.

Pandas is built on top of NumPy and uses NumPy arrays internally.

Example:

NumPy creates the array.

Pandas creates a Series from that array.

#Series
Serias is one dimansion labeled array capable of holding any data type.

Axis labels are collectively called the index.(Index=Label)

Series = One Column

In [22]:
#Import library
import numpy as np
import pandas as pd

#Creating series
alphabet=["a","b","c"] #one dimension(1D)
digit =[1,2,3]

num=[[10,20,30],
     [60,70,80]] #2D-like table(matrix)

arr = np.array([10,20,30])
d = {
    'school':"ABC school",
    "name":"Bob",
    "age":12

}

#printing series 1D
pd.Series(alphabet) #1D = Line of values

0    a
1    b
2    c
dtype: object

In [20]:
#make alphabet as index and digit as series
pd.Series(digit, index= alphabet)

a    1
b    2
c    3
dtype: int64

In [40]:
#print 2D
pd.Series(num)

0    [10, 20, 30]
1    [60, 70, 80]
dtype: object

In [13]:
#pritn array
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [14]:
#print dictionary
pd.Series(d)

school    ABC school
name             Bob
age               12
dtype: object

In [37]:
#3D - stack of table(stack of matrix)
arr = np.array([
    [[0, -3], [5, 2]],
    [[13, 1], [-4, 5]]
])

s = pd.Series(list(arr))#No native 3D structure in Pandas

print(s)
print(arr.ndim)# show dimention number -3
print(arr.shape)#number of- matrices, rows, columns(2,2,2)

"""
Matrix-A
[ 0  -3 ]
[ 5   2 ]

Matrix-B
[ 13   1 ]
[ -4   5 ]

Output-
[
    Matrix A,
    Matrix B
]

2 matrices(A,B)
2 rows per matrix
2 columns per row
"""

0     [[0, -3], [5, 2]]
1    [[13, 1], [-4, 5]]
dtype: object
3
(2, 2, 2)

'\nMatrix-A\n[ 0  -3 ]\n[ 5   2 ]\n\nMatrix-B\n[ 13   1 ]\n[ -4   5 ]\n\nOutput-\n[\n    Matrix A,\n    Matrix B\n]\n\n2 matrices(A,B)\n2 rows per matrix\n2 columns per row\n'

#DataFrame
DataFrame = Full Table

A DataFrame is a two-dimensional table made up of rows and columns.

Entire table → DataFrame

Name column only → Series

Salary column only → Series

In [ ]:
#creating DataFrames
data = {
    'name': ['John','Bob','Arica','Anna'],
    'Age':[]
}